name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler: '2.6.9'
          bundler-cache: true

      - name: Set locale
        run: |
          echo "LANG=ja_JP.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=ja_JP.UTF-8" >> $GITHUB_ENV

      - name: Build Jekyll
        run: |
          cd paz-site
          bundle exec jekyll build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_PLANT_0DE033F10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/paz-site"
          output_location: "_site"
          skip_app_build: true
